version: '2'
services:

    db:
        build: mongo/.
        environment:
            MONGO_INITDB_DATABASE: movies
        ports:
        - 27018:27017
        volumes:
            - ./mongo/mongo-volume:/data/db
    
    movies:
        build: ms-movie/.
        depends_on: 
            - db
        ports:
            - "5000:5000"
    ratings:
        build: ms-ratings/.
        depends_on: 
            - db
        ports:
            - "5001:5000"
